#name: Notify Slack on PR
#
#on:
#  push:
#    branches:
#      - tool/3-modify-pr-slack-alarm
#
#jobs:
#  notify:
#    runs-on: ubuntu-latest
#    steps:
#      - name: Send Slack Notification
#        uses: 8398a7/action-slack@v3
#        with:
#          status: ${{ job.status }}
#          fields: repo,message,commit,author
#          author_name: Setting Backend - dev
#          mention: here
#          if_mention: failure,cancelled
#          text: |
#            New PR opened: <${{ github.event.pull_request.html_url }}|#${{ github.event.pull_request.number }}>
#            Title: ${{ github.event.pull_request.title }}
#
#            Repository: ${{ github.repository }}
#            Commit: ${{ github.sha }}
#            Author: ${{ github.event.pull_request.user.login }}
#        env:
#          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}