name: Notify Slack on PR

on:
  push:
    branches:
      - tool/3-pr-slack-alarm

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: send slack message
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: workflow,job,commit,message,ref,author,took
        custom_payload: |
          {
            "text": "PR #${{ github.event.pull_request.number }} by ${{ github.event.pull_request.user.login }} is opened.\nTitle:\n${{ github.event.pull_request.title }}"
          }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
