name: Notify Slack on PR

on:
  push:
    branches:
      - tool/3-modify-pr-slack-alarm

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR Details
        id: pr-details
        run: |
          echo "PR_NUMBER=${{ github.event.pull_request.number }}" >> $GITHUB_OUTPUT
          echo "PR_TITLE=${{ github.event.pull_request.title }}" >> $GITHUB_OUTPUT

      - name: Send Slack Notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,message,commit,author
          author_name: Setting Backend - dev
          mention: here
          if_mention: failure,cancelled
          text: |
            New PR opened: <${{ github.event.pull_request.html_url }}|#${{ steps.pr-details.outputs.PR_NUMBER }}>
            Title: ${{ steps.pr-details.outputs.PR_TITLE }}
          custom_payload: |
            {
              "attachments": [{
                "color": "good",
                "fields": [
                  {
                    "title": "Repository",
                    "value": "${{ github.repository }}",
                    "short": true
                  },
                  {
                    "title": "PR Number",
                    "value": "#${{ steps.pr-details.outputs.PR_NUMBER }}",
                    "short": true
                  },
                  {
                    "title": "PR Title",
                    "value": "${{ steps.pr-details.outputs.PR_TITLE }}",
                    "short": false
                  },
                  {
                    "title": "Commit",
                    "value": "${{ github.sha }}",
                    "short": true
                  },
                  {
                    "title": "Author",
                    "value": "${{ github.actor }}",
                    "short": true
                  }
                ]
              }]
            }
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}